import requests
import os
import sys

HEADER_FILE = "syscall_numbers.h"

def get_version_str() -> str:
    kernel_release = os.uname().release
    # i only want the major and minor numbers
    version = ".".join(kernel_release.split(".")[:2])
    return f"v{version}"

def fetch_syscall_table() -> str:
    version = get_version_str()
    print(f"fetching syscalls for kernel version {version}")
    url = f"https://raw.githubusercontent.com/torvalds/linux/{version}/arch/x86/entry/syscalls/syscall_64.tbl"
    resp = requests.get(url)

    if resp.status_code != 200:
        print("error fetching syscalls")
        sys.exit(1)

    return resp.text

def get_syscalls() -> list[str|None]:
    table = fetch_syscall_table()
    table_lines = table.splitlines()

    # find the end of the leading comment
    for i, line in enumerate(table_lines):
        if not line.startswith("#"):
            comment_end = i
            break
    
    syscall_lines = table_lines[comment_end:]
    syscalls = [None] * 512

    max_number = -1
    for line in syscall_lines:
        # this line isn't a syscall
        if not line or not line[0].isnumeric():
            continue

        number, abi, name, *_ = line.split()
        if abi in ("64", "common"):
            number = int(number)

            syscalls[number] = name
            max_number = max(max_number, number)

    return syscalls[:max_number + 1]

def write_header(syscalls: list[str|None]) -> None:
    with open(HEADER_FILE, "w") as header:
        header.write("// This header is autogenerated by `extract_syscall_numbers.py`.\n")
        header.write(f"// It extracted the syscall numbers from https://raw.githubusercontent.com/torvalds/linux/{get_version_str()}/arch/x86/entry/syscalls/syscall_64.tbl\n\n")

        header.write(f"#define NUM_SYSCALLS {len(syscalls)}\n")
        syscalls_str = ", ".join([
            f"\"{syscall}\"" if syscall else f"\"INVALID[{i}]\"" 
            for i, syscall in enumerate(syscalls)
        ])
        header.write(f"const char *syscall_numbers[NUM_SYSCALLS] = {{{syscalls_str}}};\n")

def main() -> None:
    syscalls = get_syscalls()
    write_header(syscalls)

if __name__ == "__main__":
    main()
